general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size=12

[cursor.style]
blinking = "Always"

[window]
padding.y = 10
padding.x = 10
decorations = "Buttonless"
option_as_alt = "Both"

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "cd ~; exec $SHELL"]

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
    { key = "N", mods = "Command", action = "CreateNewWindow" },
    { key = "T", mods = "Command", action = "CreateNewTab" },
]
